#!/bin/bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

# This script is the release gate and CI entry point. `set -euo pipefail` makes
# every assertion fatal, treats missing variables as errors, and preserves a
# failure from either side of a pipeline.
# All host-generated state lives under /tmp and is removed on every exit. Empty
# defaults keep cleanup valid even when an early syntax/lint assertion fails.
pycache_root=$(mktemp -d /tmp/clawhunter-pycache-XXXXXX)
tmp_one=""
tmp_two=""
install_root=""
cleanup_gate() {
    rm -rf "$pycache_root"
    [ -z "$tmp_one" ] || rm -rf "$tmp_one"
    [ -z "$tmp_two" ] || rm -rf "$tmp_two"
    [ -z "$install_root" ] || rm -rf "$install_root"
}
trap cleanup_gate EXIT

# Phase 1: reject syntax and portability warnings across every shipped/tested
# shell file, then byte-compile all Python entry points and fixtures.
mapfile -t shell_files < <(find lib payloads scripts tests -type f -name '*.sh' | sort)
bash -n "${shell_files[@]}"
# Warning severity is intentional: portability and quoting warnings are release
# failures for code that runs with firmware-provided variables and BusyBox tools.
shellcheck -S warning "${shell_files[@]}"
# Byte-compilation catches parser/import-time errors. Redirecting Python's cache
# prefix keeps generated bytecode out of both the worktree and release archive.
PYTHONPYCACHEPREFIX="$pycache_root" python3 -m py_compile \
    payloads/user/reconnaissance/clawhunter/harvest.py \
    tests/fixtures/openclaw_server.py \
    tests/test_harvest.py
# Phase 2: exercise evidence classification and protocol/report helpers without
# requiring a live OpenClaw gateway or Pager hardware.
# The shell test includes a loopback HTTP/WebSocket integration fixture in
# addition to in-process classifier cases.
bash tests/test_common.sh
PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover -s tests -p 'test_*.py' -v

# Parity is structural as well as behavioral: sequential and parallel parent
# paths must both use the one validated checkpoint writer from common.sh.
[ "$(grep -c 'checkpoint_mark "\$CHECKPOINT_FILE"' \
    payloads/user/reconnaissance/clawhunter/payload.sh)" -eq 2 ]

# Phase 3: guard the load-bearing unified-version invariant. The expression
# reads declarations/comments from all runtime files and permits one value only.
versions=$(sed -nE \
    's/.*(VERSION|PAYLOAD_VERSION)[=: ]+"?([0-9]+\.[0-9]+\.[0-9]+)"?.*/\2/p' \
    lib/common.sh \
    payloads/user/reconnaissance/clawhunter/payload.sh \
    payloads/recon/access_point/clawhunter/payload.sh \
    payloads/alerts/pineapple_client_connected/clawhunter-watchdog/payload.sh \
    payloads/user/reconnaissance/clawhunter/harvest.py \
    scripts/package-release.sh \
    | sort -u)
# One unique value is necessary but not sufficient; require the intended release
# value explicitly so an accidental unified downgrade also fails.
[ "$versions" = "3.4.0" ] || {
    printf 'Version mismatch:\n%s\n' "$versions" >&2
    exit 1
}
# User-facing release surfaces are not parsed as runtime declarations, so assert
# their exact current markers separately to catch stale badge/install/changelog.
grep -q 'version-3.4.0-green' README.md
grep -q '^## \[v3.4.0\] - 2026-08-09$' CHANGELOG.md
grep -q 'CLAWHunter v3.4.0 installed' scripts/install-pager.sh
grep -q 'CLAWHunter v3.4.0 Architecture' docs/architecture.dot
# Reject the obsolete numeric VIBRATE form: current Pager firmware expects a
# filename or complete RTTTL string for every direct/shared haptic invocation.
! rg -n 'VIBRATE[[:space:]]+[0-9]+' lib payloads

# Phase 4: build twice into independent directories, compare bytes, inspect the
# Portal resource layout, and dry-run the installer against a temporary root.
tmp_one=$(mktemp -d /tmp/clawhunter-build-one-XXXXXX)
tmp_two=$(mktemp -d /tmp/clawhunter-build-two-XXXXXX)
install_root=$(mktemp -d /tmp/clawhunter-install-XXXXXX)
scripts/package-release.sh "$tmp_one" >/dev/null
scripts/package-release.sh "$tmp_two" >/dev/null
# Exact byte comparison validates tar/gzip metadata normalization, not merely an
# equivalent unpacked file set.
cmp "$tmp_one/clawhunter-v3.4.0-pager.tar.gz" "$tmp_two/clawhunter-v3.4.0-pager.tar.gz"
tar -tzf "$tmp_one/clawhunter-v3.4.0-pager.tar.gz" > "$tmp_one/archive-contents.txt"
grep -q 'payloads/user/reconnaissance/clawhunter/common.sh' "$tmp_one/archive-contents.txt"
# These assertions keep the release artifact self-contained: its README links
# remain valid even when an operator downloads the archive without cloning Git.
grep -q 'docs/V3.3-RESEARCH.md' "$tmp_one/archive-contents.txt"
grep -q 'docs/V3.4-RELEASE-NOTES.md' "$tmp_one/archive-contents.txt"
grep -q 'images/architecture.png' "$tmp_one/archive-contents.txt"
grep -q 'CONTRIBUTING.md' "$tmp_one/archive-contents.txt"
# Verify both distribution integrity layers exactly as an operator will: the
# adjacent archive checksum first, then every unpacked file in SHA256SUMS.
(
    cd "$tmp_one"
    sha256sum -c clawhunter-v3.4.0-pager.tar.gz.sha256 >/dev/null
    mkdir unpacked
    tar -xzf clawhunter-v3.4.0-pager.tar.gz -C unpacked
    cd unpacked/clawhunter-v3.4.0
    sha256sum -c SHA256SUMS >/dev/null
    # Reproducibility is cross-host, not merely twice-on-this-host: the two
    # builds above share one locale, so they cannot detect collation drift.
    # Assert the manifest is in C-locale byte order, which is what every CI
    # runner produces and therefore what a downloader rebuilding the archive
    # must be able to reproduce.
    diff <(cut -c67- SHA256SUMS) <(cut -c67- SHA256SUMS | LC_ALL=C sort) >/dev/null
)

# A staged install verifies canonical category paths and eliminates divergence
# between suite common.sh and the three Portal-local resource copies.
scripts/install-pager.sh "$install_root" >/dev/null
cmp lib/common.sh "$install_root/user/reconnaissance/clawhunter/common.sh"
cmp lib/common.sh "$install_root/recon/access_point/clawhunter/common.sh"
cmp lib/common.sh "$install_root/alerts/pineapple_client_connected/clawhunter-watchdog/common.sh"

printf 'All CLAWHunter checks passed.\n'
